### ISSUE TITLE
Sortowanie po zarobkach

### ISSUE THREAD

**Issue by klaskowski** [Czy-Jest-Eldorado/feature-requests#1]

**Comment by jkobus** [comment]
Aktualnie możemy sortować od najlepiej płatnych ofert. Co chciałbyś tu dodać?

**Comment by jkobus** [comment]
Aktualnie silnik dziala tak, że ważniejsze dla niego jest to co wpiszesz w słowach kluczowych. I mimo, że niektóre oferty z kategorii mają większą stawkę, to nadal wyżej będzie pokazywał lepsze dopasowania tematyczne, oczywiście również posortowane wg kwoty.
