### ISSUE TITLE
Dodanie daty oferty na listingu

### ISSUE THREAD

**Issue by darekmydlarz** [Czy-Jest-Eldorado/feature-requests#15]
Dodajcie datę oferty na listingu ofert. Dzięki temu widać, czy oferta jest w miarę świeża, czy to jakiś stary wpis. I widać czy aplikacja działa prawidłowo i czy na bieżąco ściąga oferty, czy np. miała jakiegoś crasha i od paru dni nic nie widać.

Pozdro!

**Comment by jkobus** [comment]
Cześć Darku. Dzięki za zgłoszenie.

Aktualnie na liście jest emoji zegarka, i po najechaniu na niego pokazuje się tooltip z informacją, z kiedy jest oferta:

![image](https://github.com/Czy-Jest-Eldorado/feature-requests/assets/1527096/7956c111-7d64-4219-908c-1ccf26bb4fdd)

Stare oferty, które się nie aktualizują z jakiegoś powodu przez co najmniej 1 dzień, mają dodatkowo ikonę nagrobka :)
