### ISSUE TITLE
Wyświetlać datę w kolumnach 

### ISSUE THREAD

**Issue by rzechu** [Czy-Jest-Eldorado/feature-requests#19]
Przydalaby się jednak data dodania/aktualizacji bo bez tego nie bardzo wiadomo czy to rekordy z przed godziny czy z przed 5 dni.
Kolumna na końcu albo przed kwotą, albo na samym początku
![image](https://github.com/Czy-Jest-Eldorado/feature-requests/assets/45091660/4df51737-c789-4857-8320-ba4350a0813e)

**Comment by jkobus** [comment]
Hej, dzięki za feedback. Było już podobne zgłoszenie tutaj: https://github.com/Czy-Jest-Eldorado/feature-requests/issues/15.

Informacja, ile czasu upłynęło od dodania oferty, jest już na liście. Trzeba najechać na zegarek. Natomiast to pytanie się powtarza, więc ten UX jest do przemyślenia.

Napisz, czy to rozwiązuje Twoje pytanie, czy nadal widziałbyś tutaj jakieś zmiany.

**Comment by rzechu** [comment]
Jak już wiem o zegarku to wystarczy, aczkolwiek osobiscie przyzwyczajony jestem ze tabela ma kolumny (pozwala tez zrobic sortowanie, chociaz tu widze ze masz na to osobny combobox w filtrze). 
Ta niby jest czytelna bez kolumn, ale jak widać na zegarku czy pracy zdalnej (dopiero teraz najechalem kursorem) nie koniecznie jest to intuicyjne.
