### ISSUE TITLE
Pozbycie się paginacji

### ISSUE THREAD

**Issue by klaskowski** [Czy-Jest-Eldorado/feature-requests#2]
12k ofert to nie dużo, można zwracać od razu
To w ogóle nie powinno musieć mieć bazy danych, da się to wszystko opędzić na SSG z Next.js

**Comment by jkobus** [comment]
Strona jest renderowana klasycznie, tj. server side. Nie ma tam żadnego frameworku JS. Jest jquery :)
Wyniki dostarczane są bezpośrednio z silnika wyszukiwarki.

Do końca życia MVP musi wystarczyć zwiększenie rozmiarów strony do 40 :)

Ogólnie zamysł jest też taki, aby wyszukiwanie było na tyle precyzyjne, żeby wyników było maksymalnie 1-2 strony.
