### ISSUE TITLE
Dodanie możliwości jednoczesnego odfiltrowania ofert pracy hybrydowej i biurowej

### ISSUE THREAD

**Issue by spidero** [Czy-Jest-Eldorado/feature-requests#20]
- przydala by sie opcja miasta (moze zakladka mapa?)
- w opcji tryb pracy przydala by sie opcja obie, w tej chwili to nieintuicyjne
- opcja umowa jw
- zakladka 15000 mi nic nie mowia (min? max?)

**Comment by jkobus** [comment]
Cześć,

Dzięki za feedback.
Aktualnie pracujemy nad nowym ux i myślę, że wszystkie sugestie będą uwzględnione. Może oprócz mapy :)

**Comment by jkobus** [comment]
Krótka aktualizacja:

Do wyszukiwarki dodana została opcja "praca hybrydowa lub biuro" :rocket:.

W przypadku umowy, są tylko 2 opcje, niezaznaczenie ich wyłącza filtrowanie wg umowy, więc opcja "obie" dałaby dokladnie taki sam rezultat.

Przy okazji wspomnę, że input z kwotą to "wynagrodzenie minimalne". Służy do odfiltrowania ofert ponizej naszych oczekiwań finansowych.
