### ISSUE TITLE
Zobacz ofertę nie przenosi na stronę danej oferty

### ISSUE THREAD

**Issue by NiceLeader** [Czy-Jest-Eldorado/feature-requests#26]

**Comment by jkobus** [comment]
Dzięki za zgłoszenie. Napisz mi proszę:

- czy dzieje się tak dla konkretnej oferty? Jaki jest jej numer/adres url?
- czy finalnie udało się otworzyć ofertę?

**Comment by NiceLeader** [comment]
1. Dla każdej jaką wybiorę
2. nie

**Comment by jkobus** [comment]
Ok, muszę jakoś odtworzyć ten problem (u mnie działa ( ͡° ͜ʖ ͡°) ).
Napisz proszę:
- jakiej przeglądarki używasz
- jaki system operacyjny
- czy próbowałeś w trybie incognito (bez cookie, cache)?
- czy masz jakieś rozszerzenia, które blokują google analytics/zwiększają prywatność przeglądania?

Ostatnio dodałem funkcję trakującą GA do tego przycisku (zmiana weszła 4 dni temu). 
Myślę, że to może mieć związek.

Dzięki jeszcze raz za zgłoszenie.

**Comment by jkobus** [comment]
Ok, dodałem szybki fix, sprawdź proszę czy teraz działa.

**Comment by NiceLeader** [comment]
wygląda na sprawne :)

**Comment by jkobus** [comment]
Ostatnio widziałem w statystykach, że jest wiele zduplikowanych kliknięć i nie do końca rozumiałem, skąd taki efekt.
Twoje zgłoszenie pomogło rozwiązać ten problem. Dzięki!

**Comment by NiceLeader** [comment]
Nie ma problemu, pożyteczny projekt
