### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by NiceLeader** [Czy-Jest-Eldorado/feature-requests#29]
Aplikacja jest bardzo pomocna i jestem wielkim fanem jej funkcji. Mam jednak propozycję, która moim zdaniem mogłaby poprawić wygodę korzystania z narzędzia, zwłaszcza dla użytkowników pracujących w nocy lub w słabym oświetleniu.

Chciałbym zgłosić prośbę o dodanie trybu ciemnego (dark mode) do interfejsu użytkownika.

**Comment by jkobus** [comment]
Dzięki. Dodane do baklogu :)

**Comment by jkobus** [comment]
Done
![image](https://github.com/user-attachments/assets/9e8c8de2-232d-4922-8136-c1b2dc06682a)
