### ISSUE TITLE
[UX] Dodanie przycisku "Aplikuj" na liście ofert

### ISSUE THREAD

**Issue by NumerDev** [Czy-Jest-Eldorado/feature-requests#32]
Cześć, 

Od pewnego czasu brakuje mi na stronie pewnej funkcjonalności dzięki której byłbym w stanie od razu przejść z wyszukiwarki do interesującej oferty zamiast klikać  **rekord** => **aplikuj** => **wracać do strony** => **wyłączać moda**l i szukać kolejnej oferty.

Dodanie przycisku "Aplikuj" z tego modalu bezpośrednio na listę byłoby dużym czasowym usprawnieniem.
![obraz](https://github.com/user-attachments/assets/07beb277-4db5-4d11-9226-100e231f9e15)

<hr>

Drugi element, który dzisiaj został zmieniony dotyczy filtrów. Nowy UI strony wygląda bardzo przyjemnie, lecz UXowo staje się uciążliwy przez dostęp do filtrów, które zostały ukryte pod przyciskiem co zabiera niepotrzebnie czas na przeklikiwanie i staje się po dłuższym czasie irytujące. Tutaj wystarczyło by przenieść podstawowe filtry, dostępne w starej wersji zaraz pod wyszukiwarkę a bardziej zaawansowane zostawić pod przyciskiem:

![obraz](https://github.com/user-attachments/assets/eca7225f-71e8-4c62-b211-0c34ddb0479f)

**Comment by jkobus** [comment]
**Przycisk aplikuj z listy**
Myślałem o przycisku aplikowania bezpośrednio z listy, ale już nie zmieściłem tego w tej aktualizacji. Pełna zgoda - dodam.

**Filtry**
Ja nie chcę żebyście korzystali z filtrów :) 

Już wyjaśniam dlaczego: wszystkie pola, po których można filtrować dane są indeksowane. Tzn. że wpisując "admin" znajdziesz wszystkie oferty z kategorii "admin". Tak samo z trybem pracy i rodzajem kontraktu. 

Nie wszystkie dane są też poprawnie indeksowane poprzez braki w danych źródłowych. Filtrowanie wyklucza poprawne oferty, które po prostu albo zostały źle wprowadzone w serwisie źródłowym albo oferta nie zawiera takich informacji. Dlatego np. nie ma filtrowania po seniority - czasami pole jest puste ale w tytule jest napisane "senior". 

Jeśli masz jakieś przemyślenia na ten temat to oczywiście jestem otwarty na zmiany w UI/UX, natomiast ja bym sugerował nie korzystać z filtrów, w formie eksperymentu - i daj znać czy to zwraca lepsze/gorsze rezultaty.

Zerknij też na wskazówki wyszukiwania dostępne po kliknięciu w kółeczko ze znakiem zapytania.

I dzięki za makiety :) super

**Comment by NumerDev** [comment]
Okej, teraz rozumiem 😄
W takim razie nie wygodniej by było po wybraniu filtra dorzucić jego wartości prosto do query search'a? A przynajmniej te, o których mówiłeś?

**Comment by jkobus** [comment]
Robimy "pod maską" sporo optymalizacji – wprowadzamy synonimy, wykluczenia, rankingowanie, analizując, jak użytkownicy szukają informacji.

To, o czym piszesz, jest do zrobienia, ale pozostaje pytanie – po co wtedy filtry? Mam wrażenie, że to potrzeba wynikająca z przyzwyczajeń z innych stron, gdzie zanim zobaczysz coś sensownego, musisz wszystko wyklikać. Ukryłem filtry, żeby stopniowo odwarunkowywać użytkowników od tego przyzwyczajenia – być może niesłusznie, czas pokaże. :)

**Comment by jkobus** [comment]
Ok, co do przycisku "quick apply", wygląda to tak:

![image](https://github.com/user-attachments/assets/04a56c60-0b69-44af-9585-5694d39ab4f5)

Po najechaniu na ofertę w wierszu, z jego prawej strony pojawia się przycisk - jest to link, który można otworzyć środkowym przyciskiem w nowej karcie w tle, lub kliknąć. Po powrocie kliknięta oferta będzie miała czerwony wskaźnik z boku, aby było można określić, gdzie skończyliśmy. Wskaźnik znika po odświeżeniu strony.

**Comment by NumerDev** [comment]
Wygląda super, działa też bardzo dobrze 😄
